name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies (ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/npm
            web/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        run: npm ci
        working-directory: web

      - name: Lint frontend
        run: npm run lint
        working-directory: web
        continue-on-error: true

      - name: Test frontend
        run: npm run test
        working-directory: web
        continue-on-error: true

      - name: Clean previous build
        run: |
          rm -rf ../dist || true
        shell: bash
        working-directory: web

      - name: Build frontend for Tauri compilation
        run: |
          echo "Building frontend for Tauri compilation..."
          npm run build
          echo "Frontend build completed"
          ls -la ../dist || (echo "dist directory not found in workspace root" && exit 1)
        working-directory: web

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Test Rust
        run: cargo test --workspace --all-targets

      - name: Build release
        run: cargo build --release --workspace

  build-tauri:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            args: "--target aarch64-apple-darwin"
          - os: ubuntu-22.04
            args: "--target x86_64-unknown-linux-gnu"
          - os: windows-latest
            args: "--target x86_64-pc-windows-msvc"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin' || '' }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/npm
            web/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        run: npm ci
        working-directory: web

      - name: Clean previous build
        run: |
          rm -rf ../dist || true
        shell: bash
        working-directory: web

      - name: Build frontend
        run: |
          echo "Building frontend..."
          npm run build
          echo "Frontend build completed"
          ls -la ../dist || (echo "dist directory not found in workspace root" && exit 1)
        working-directory: web

      - name: Verify frontend dist exists
        run: |
          echo "Checking for dist directory in workspace root..."
          ls -la dist || (echo "dist directory not found in workspace root" && exit 1)

      - name: Build Tauri app
        run: |
          cd src-tauri
          cargo build --release ${{ matrix.args }}
